import Foundation

// MARK: - ARRAY CARS:

var arrayCars: [Car] = [
    Car(name: "BMW 5 Seris M Style", price: 162775, photos: [#imageLiteral(resourceName: "bmw1"), #imageLiteral(resourceName: "bmw2"), #imageLiteral(resourceName: "bmw3")], year: 2023, typeTransmission: .automatic, sizeEngine: 3.0, typeEngine: .hybrid, typeBody: .sedan, odometer: 10000, powerReserve: 1000, wheelDrive: .allWheelDrive, color: "Синий", registration: .removedRegister, power: 540, fuelFlow: 5.0, top: true, vin: true, city: "Минск", date: "20 мая", vinNumber: 203632345, description: "Новая машина", exterior: [.disk, .toner], safety: [.abs, .antiDrift, .immobilizer], comfort: [.multimedia, .autoStart, .cruiseControl, .electro], multimedia: [.aux, .bluetooth, .cd, .usb], change: .changeOff, seller: "Частное лицо"),

    Car(name: "Mercedes MLS Class", price: 223320, photos: [#imageLiteral(resourceName: "merc3"), #imageLiteral(resourceName: "merc2"), #imageLiteral(resourceName: "merc1")], year: 2023, typeTransmission: .manual, sizeEngine: 2.8, typeEngine: .diesel, typeBody: .hatchback, odometer: 5000, powerReserve: 850, wheelDrive: .allWheelDrive, color: "Фиолетовый", registration: .onRegister, power: 600, fuelFlow: 4.0, top: false, vin: false, city: "Brest", date: "05 июня", vinNumber: 434612387, description: "Новая машина", exterior: [.disk, .spoiler, .toner], safety: [.signalization, .abs, .esp, .antiDrift], comfort: [.cruiseControl, .multimedia], multimedia: [.bluetooth, .usb, .cd], change: .changeOn, seller: "Автохаус"),
    
    Car(name: "Speed Car Future Model", price: 145169, photos: [#imageLiteral(resourceName: "speed1"), #imageLiteral(resourceName: "speed2"), #imageLiteral(resourceName: "speed3")], year: 2023, typeTransmission: .automatic, sizeEngine: 4.2, typeEngine: .hybrid, typeBody: .sedan, odometer: 2000, powerReserve: 0, wheelDrive: .frontWheelDrive, color: "Пурпурный", registration: .onRegister, power: 720, fuelFlow: 6.2, top: true, vin: true, city: "Витебск", date: "12 августа", vinNumber: 319632310, description: "Новая машина", exterior: [.toner, .disk], safety: [.antiDrift, .esp, .immobilizer], comfort: [.cruiseControl, .multimedia], multimedia: [.cd, .usb, .bluetooth], change: .changeOff, seller: "Частное лицо")
]
